import { CiUser } from "react-icons/ci";
import { IoStarSharp } from "react-icons/io5";
import { FaUserFriends } from "react-icons/fa";


export const products = [
    {
        id: 1,
        title: "Clean Code برای برنامه نویسان JS",
        description: "فرق بین یه برنامه‌نویس تازه‌کار و حرفه‌ای نوع دیدگاه و طرز کدنویسیشونه. برنامه‌نویس حرفه‌ای کدی رو می‌نویسه که تست‌پذیر باشه،…",
        image: "images/clean-code.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 231,
        price: "1,650,000 تومان",
    },
    {
        id: 2,
        title: "زیر و بَم و منطق دیپلوی برای برنامه نویسان JS",
        description: "تو هر فیلدی فعالیت بکنی برای پرزنت خودت تو بازار کار و نمایش نمونه کارات نیاز به دپلوی…",
        image: "images/deploy.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 408,
        price: "1,199,500 تومان",
    },
    {
        id: 3,
        title: "آموزش جامع پروژه محور GraphQL",
        description: "واسه حرفه‌ای‌تر شدن و استخدام تو شرکت های بزرگ با حقوق های بالا باید Graph رو بلد باشی…",
        image: "images/graphql.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 589,
        price: "187,500 تومان",
    },
    {
        id: 4,
        title: "آموزش پروژه محور WebSocket",
        description: "با Socket می‌تونی مثل تلگرام یا سایت های ارز دیجیتال یه ارتباط Realtime بسازی و بدون نیا…",
        image: "images/websocket.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 589,
        price: "221,250 تومان",
    },
    {
        id: 5,
        title: "آموزش تخصصی Redux مقدماتی تا پیشرفته",
        description: "باریداکس یه کتابخونه پراستفاده واسه مدیریت حالت های مختلف یه برنامه جاوا اسکریپتیه که…",
        image: "images/redux.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 1447,
        price: "700,000 تومان",
    },
    {
        id: 6,
        title: "آموزش ۲۰ کتابخانه کاربردی ReactJS برای بازارکار",
        description: "‌کتابخانه‌ها باعث افزایش سرعت کدنویسی میشن. در حدی که تو بازار کار هم از کتابخانه…",
        image: "images/reactjs.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 1447,
        price: "285,000 تومان",
    },



    {
        id: 7,
        title: "پروژه های خلاقانه با جاوااسکریپت",
        description: "ممکن است در خیلی از وب سایت ها و شبکه های مجازی پروژه هایی را دیده باشید که خیلی…",
        image: "images/js.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 1024,
        price: "410,000 تومان",
    },
    {
        id: 8,
        title: "آموزش رایگان ویو جی اس مقدماتی تا پیشرفته",
        description: "در دوره آموزش رایگان ویو جی اس مقدماتی تا پیشرفته میتونی ویو جی اس رو خیلی راحت با…",
        image: "images/vue.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 23482,
        price: "رایگان",
    },
    {
        id: 9,
        title: "آموزش کاربردی Vscode | مقدماتی تا پیشرفته",
        description: "یکی از دلایل محبوبیت وی اس کد، حجم پایین، داشتن اکستنشن های کاربردی مختلف،رو بلد باشی…",
        image: "images/graphql.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 25767,
        price: "رایگان",
    },
    {
        id: 10,
        title: "آموزش NPM برای جاوااسکریپت کارها",
        description: "به صورت خلاصه، NPM یک پکیج منیجر است. در اصل نود جی اس یک پکیج منیجر به اسم…",
        image: "images/npm.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 20072,
        price: "رایگان",
    },
    {
        id: 11,
        title: "آموزش Canvas برای برنامه نویسان فرانت‌اند",
        description: "Canvas عمدتا برای پیاده سازی و رسم نمودار های مختلف جهت تحلیل اطلاعات، بک‌گراندها و افکت های متنی انیمیشنی، شکل……",
        image: "images/canvas.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 558,
        price: "221,250 تومان",
    },
    {
        id: 12,
        title: "Api نویسی با Nodejs",
        description: "‌شما بعد از گذروندن این دوره میتونین واسه پروژه هایی که تو زمینه فرانت‌اند توسعه…",
        image: "images/node-js.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 496,
        price: "435,000 تومان",
    },
    {
        id: 13,
        title: "Clean Code برای برنامه نویسان JS",
        description: "فرق بین یه برنامه‌نویس تازه‌کار و حرفه‌ای نوع دیدگاه و طرز کدنویسیشونه. برنامه‌نویس حرفه‌ای کدی رو می‌نویسه که تست‌پذیر باشه،…",
        image: "images/clean-code.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 231,
        price: "1,650,000 تومان",
    },
    {
        id: 14,
        title: "زیر و بَم و منطق دیپلوی برای برنامه نویسان JS",
        description: "تو هر فیلدی فعالیت بکنی برای پرزنت خودت تو بازار کار و نمایش نمونه کارات نیاز به دپلوی…",
        image: "images/deploy.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 408,
        price: "1,199,500 تومان",
    },
    {
        id: 15,
        title: "آموزش جامع پروژه محور GraphQL",
        description: "واسه حرفه‌ای‌تر شدن و استخدام تو شرکت های بزرگ با حقوق های بالا باید Graph رو بلد باشی…",
        image: "images/graphql.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 589,
        price: "187,500 تومان",
    },
    {
        id: 16,
        title: "آموزش پروژه محور WebSocket",
        description: "با Socket می‌تونی مثل تلگرام یا سایت های ارز دیجیتال یه ارتباط Realtime بسازی و بدون نیا…",
        image: "images/websocket.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 589,
        price: "221,250 تومان",
    },
    {
        id: 17,
        title: "آموزش تخصصی Redux مقدماتی تا پیشرفته",
        description: "باریداکس یه کتابخونه پراستفاده واسه مدیریت حالت های مختلف یه برنامه جاوا اسکریپتیه که…",
        image: "images/redux.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 1447,
        price: "700,000 تومان",
    },
    {
        id: 18,
        title: "آموزش ۲۰ کتابخانه کاربردی ReactJS برای بازارکار",
        description: "‌کتابخانه‌ها باعث افزایش سرعت کدنویسی میشن. در حدی که تو بازار کار هم از کتابخانه…",
        image: "images/reactjs.webp",
        teachers: "محمدامین سعیدی راد",
        teachersLogo: <CiUser style={{fontSize: "20px"}}/>,
        logo: <IoStarSharp style={{fontSize: "20px"}}/>,
        participant: <FaUserFriends style={{fontSize: "20px"}}/>,
        participantCount: 1447,
        price: "285,000 تومان",
    },
];